<?php

namespace ContainerErrQsAY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslation_Extractor_Visitor_ConstraintService extends App_KernelProdContainer
{
    /*
     * Gets the private 'translation.extractor.visitor.constraint' shared service.
     *
     * @return \Symfony\Component\Translation\Extractor\Visitor\ConstraintVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['translation.extractor.visitor.constraint'] = new \Symfony\Component\Translation\Extractor\Visitor\ConstraintVisitor([0 => 'TimeInterval', 1 => 'All', 2 => 'AtLeastOneOf', 3 => 'Bic', 4 => 'Blank', 5 => 'Callback', 6 => 'CardScheme', 7 => 'Choice', 8 => 'Cidr', 9 => 'Collection', 10 => 'Compound', 11 => 'Count', 12 => 'Country', 13 => 'CssColor', 14 => 'Currency', 15 => 'DateTime', 16 => 'Date', 17 => 'DivisibleBy', 18 => 'Email', 19 => 'EqualTo', 20 => 'ExpressionSyntax', 21 => 'Expression', 22 => 'File', 23 => 'GreaterThanOrEqual', 24 => 'GreaterThan', 25 => 'Hostname', 26 => 'Iban', 27 => 'IdenticalTo', 28 => 'Image', 29 => 'Ip', 30 => 'IsFalse', 31 => 'IsNull', 32 => 'IsTrue', 33 => 'Isbn', 34 => 'Isin', 35 => 'Issn', 36 => 'Json', 37 => 'Language', 38 => 'Length', 39 => 'LessThanOrEqual', 40 => 'LessThan', 41 => 'Locale', 42 => 'Luhn', 43 => 'NotBlank', 44 => 'NotCompromisedPassword', 45 => 'NotEqualTo', 46 => 'NotIdenticalTo', 47 => 'NotNull', 48 => 'Range', 49 => 'Regex', 50 => 'Sequentially', 51 => 'Time', 52 => 'Timezone', 53 => 'Type', 54 => 'Ulid', 55 => 'Unique', 56 => 'Url', 57 => 'Uuid', 58 => 'Valid', 59 => 'When', 60 => 'Expression', 61 => 'Email', 62 => 'NotCompromisedPassword', 63 => 'When', 64 => 'UniqueEntity', 65 => 'UserPassword']);
    }
}
