<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErrQsAY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErrQsAY/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerErrQsAY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerErrQsAY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerErrQsAY\App_KernelProdContainer([
    'container.build_hash' => 'ErrQsAY',
    'container.build_id' => '500534dc',
    'container.build_time' => 1686744714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErrQsAY');
