<?php

namespace ContainerTFyJX2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhatSQqService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JhatSQq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JhatSQq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'workRecordRepository' => ['privates', 'App\\Repository\\WorkRecordRepository', 'getWorkRecordRepositoryService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'workRecordRepository' => 'App\\Repository\\WorkRecordRepository',
        ]);
    }
}
