<?php

namespace ContainerTFyJX2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FaLKlJnService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.faLKlJn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.faLKlJn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'workRecordRepository' => ['privates', 'App\\Repository\\WorkRecordRepository', 'getWorkRecordRepositoryService', true],
        ], [
            'entityManager' => '?',
            'workRecordRepository' => 'App\\Repository\\WorkRecordRepository',
        ]);
    }
}
