<?php

namespace ContainerTFyJX2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeIntervalValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\TimeIntervalValidator' shared autowired service.
     *
     * @return \App\Validator\TimeIntervalValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\TimeIntervalValidator'] = new \App\Validator\TimeIntervalValidator();
    }
}
