<?php

namespace ContainerTFyJX2N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkRecordRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\WorkRecordRepository' shared autowired service.
     *
     * @return \App\Repository\WorkRecordRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\WorkRecordRepository'] = new \App\Repository\WorkRecordRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
